### ISSUE TITLE
Fix _predict_distances workaround in distance.py

### ISSUE THREAD

**Issue by gcattan** [pyRiemann/pyRiemann-qiskit#245]
![image](https://github.com/pyRiemann/pyRiemann-qiskit/assets/6229031/96885ba1-34ff-49e1-92dd-640eb53caec0)

              
We should take advantage of this PR to remove this weird trick.
In truth, `MDM` class should not be imported in this file.

_Originally posted by @qbarthelemy in https://github.com/pyRiemann/pyRiemann-qiskit/pull/244#discussion_r1500481441_

**Comment by qbarthelemy** [comment]
In addition to removing workaround from distance.py, we must correct the prediction methods of `QuanticMDM`.

**Comment by gcattan** [comment]
I still would like to give a try to a constraint programming (CP) implementation of the prediction steps.
What I suggest is:
- to rename the current "logeuclid distance" to "logeuclid distance to convex hull".
- to introduce a new "euclid distance" and "logeuclid distance"

To use CP, we would need to accept a slightly different signature for the distance method: `cpm_dist(means, trial)`, and not only `dist(mean, trial)`. Hence the workaround (but we can think of a better solution, with inheritance, or by composition, but by overriding only the method in the instance and not in the class). But the idea is that the user will put whatever distance or cpm_distance he wants.

Although I 100% agree we need to separate the MDM from NCH, it could be interesting to investigate this mixing at some point. Not that I expect something exceptional, but just for the research question ^^

We don't need to put any of these results in the publication. We can focus on MDM with quantum training, and NCH with quantum prediction. 

@toncho11 FYI

**Comment by gcattan** [comment]
Fix in #248
