### ISSUE TITLE
Migrate to Qiskit 1.0

### ISSUE THREAD

**Issue by frankharkins** [pyRiemann/pyRiemann-qiskit#265]
I'm making this issue because this project is part of the [Qiskit ecosystem](https://qiskit.github.io/ecosystem/).

As of June 2024, we're introducing a requirement that all projects are compatible with Qiskit 1.0. New users will be using Qiskit 1.0 and we want to make sure any projects we guide them to work straight away.

See our [migration guide](https://docs.quantum.ibm.com/api/migration-guides). and let me know if you need any support (such as answering questions about Qiskit or code review). With Qiskit's new stability policy, this should be the last change needed for a while.

In June, we will test out your project and remove it if it doesn't work with Qiskit 1.0. This includes cases in which we can't get the project working because the documentation is lacking. We do value your project so let me know if you need any help migrating or have any other concerns.

**Comment by gcattan** [comment]
@qbarthelemy @toncho11 I think we can release v0.2 and start working on updating the dependencies.

@frankharkins Is it June 1st or June 30th? Can you point us to the requirement (test and doc?) 
Your help will be greatly appreciated :)

**Comment by frankharkins** [comment]
We don't have a set date since it'll take a while to test all the ecosystem projects. If you need more time we can wait until later in the month. Even if you can't hit that in time, we can grant an extension if you're actively working on it, or in the worst-case scenario you can reapply when you do manage to migrate.

It'll be a manual test in which we'll clone your repo, try and run the tests using Qiskit 1.0, and maybe try out a code example or two. We'll communicate any problems we find and give opportunity to address them before we do any removing.

We generally don't want to remove projects, so any we do remove would have to be very broken or making no effort to migrate to Qiskit 1.0. I don't think that's a problem here.

Let me know if I can help at all!

**Comment by toncho11** [comment]
So the migration to Qiskit 1.0 is complete?

**Comment by gcattan** [comment]
Yes :) @frankharkins it is ready to test, feedback are welcomed :)

**Comment by frankharkins** [comment]
All good, thanks for working on this 😄
