### ISSUE TITLE
[Child] Add docplex to setup.py

### ISSUE THREAD

**Issue by gcattan** [pyRiemann/pyRiemann-qiskit#32]
As a prerequiste for #27, it is necessary to add `docplex==2.19.202` the `setup.py` file:

![image](https://user-images.githubusercontent.com/6229031/152792526-b772772d-4674-43aa-9798-82c87a7f4cab.png)

@toncho11 it is a good first issue, if you want to contribute :)

**Comment by toncho11** [comment]
#33
