### ISSUE TITLE
Using stored Qiskit TOKEN 

### ISSUE THREAD

**Issue by toncho11** [pyRiemann/pyRiemann-qiskit#45]
It could be made q_account_token='load_account' and then it calls load_account() instead of using the string as a token.
The user must have performed "save_account" before that.

This is how account management is done in general:

```
from qiskit import IBMQ

IBMQ.save_account("fgsfgsdfsdfsdfsdfsdfaasdgfsadgdsfgdfsgsfdgsdfgsdfghdf")

IBMQ.load_account()
```

**Comment by gcattan** [comment]
@toncho11 feel free to close if the issue is resolved
