### ISSUE TITLE
Use Pegasos implementation of QSVC

### ISSUE THREAD

**Issue by gcattan** [pyRiemann/pyRiemann-qiskit#49]
G. Gentinetta, A. Thomsen, D. Sutter, and S. Woerner, ‘The complexity of quantum support vector machines’, arXiv, arXiv:2203.00031, Feb. 2022. doi: [10.48550/arXiv.2203.00031](https://doi.org/10.48550/arXiv.2203.00031).

Available in Qiskit ML:
https://github.com/Qiskit/qiskit-machine-learning/blob/main/qiskit_machine_learning/algorithms/classifiers/pegasos_qsvc.py

**Comment by toncho11** [comment]
From the quick look of the article I think it only contains analysis and not a new implementation of QSVC?

**Comment by gcattan** [comment]
Sorry for the short issue description. The article suggests that a QSVCs based on Pegasos algorithms have a better time complexity than other QSVCs implementation.
There is an implementation of Pegasos-QSVC in Qiskit. It already inherits from ClassifierMixin, so I think it will be relatively easy to integrate it in our wrapper.
