### ISSUE TITLE
cvxpy import in example

### ISSUE THREAD

**Issue by gcattan** [pyRiemann/pyRiemann-qiskit#5]
Why do you need this import, since the example does not use any functions/classes from this package?

_Originally posted by @qbarthelemy in https://github.com/pyRiemann/pyRiemann-qiskit/pull/2#discussion_r717007925_

**Comment by gcattan** [comment]
Documenting the error:

![image](https://user-images.githubusercontent.com/6229031/144632384-f1f161cf-03a1-44f5-87c5-49222d0348c5.png)

![image](https://user-images.githubusercontent.com/6229031/144636120-9c50626b-00e2-4ef1-8575-e6d09e174103.png)

Possible solution:

apt-get -y install build-essential

**Comment by qbarthelemy** [comment]
Solved with #17
