### ISSUE TITLE
v0.0.2-dev

### ISSUE THREAD

**Issue by gcattan** [pyRiemann/pyRiemann-qiskit#69]
@toncho11 @qbarthelemy @sylvchev 
We finished the Qiskit migration (plus a couple of PRs), and I think we can release v0.0.2-dev.
What do you think?

I would like also to suggest submitting the code base to [JOSS](https://joss.theoj.org/about). It is a journal specialized in software review. It takes the form of a Github review where the reviewers directly create issues in the repo. Besides a publication, I think it can be a good idea to bring new contributors to the project. What is your opinion on this?

**Comment by toncho11** [comment]
Sounds good :)

**Comment by sylvchev** [comment]
Yes, good idea!

**Comment by qbarthelemy** [comment]
Yes, good idea!

**Comment by gcattan** [comment]
Super! Thanks for the feedback :) I will start working on this then.
